// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ogr9Mr58ljIpU2sxJpIMArBMY6T718c',
    appId: '1:4674733990:web:261a88453e86972033b167',
    messagingSenderId: '4674733990',
    projectId: 'flutter-dev-uis',
    authDomain: 'flutter-dev-uis.firebaseapp.com',
    storageBucket: 'flutter-dev-uis.firebasestorage.app',
    measurementId: 'G-7ZBJQSD22H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE0xMjgdG8jeLo9V4nqPt6YKBmF8vBrM4',
    appId: '1:4674733990:android:78603eb383acca0833b167',
    messagingSenderId: '4674733990',
    projectId: 'flutter-dev-uis',
    storageBucket: 'flutter-dev-uis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpBPhTYvJiO_oARe64ZJxaMYHu8dmPcw',
    appId: '1:4674733990:ios:9ac7b58b1955663233b167',
    messagingSenderId: '4674733990',
    projectId: 'flutter-dev-uis',
    storageBucket: 'flutter-dev-uis.firebasestorage.app',
    iosBundleId: 'com.innitech.flutteruis',
  );
}
